#!/bin/zsh

. ~/.zsh/vars

alias ls='ls --color=auto -hF'
alias ll='ls --color=auto -hFl'
alias la='ls --color=auto -hFlA'
alias m='less -S'
alias zm='zless -S'

alias c='clear'
alias cdc='cd; clear'

alias v='gvim'
alias svim='sudo gvim'

alias s='screen -DR'

alias rmf='rm -rf'

alias -g M='2>&1 | less -S'
alias -g C='| wc -l'
alias -g S='| sort'
alias -g US='| sort -u'

