#!/bin/zsh

. ~/.zsh/vars

alias ls='ls --color=auto -hF'
alias ll='ls --color=auto -hFl'
alias la='ls --color=auto -hFlA'

alias t='tree -hF --dirsfirst'
alias tl='tree -hFugp --dirsfirst'
alias ta='tree -hFugpa --dirsfirst'
alias tfi='tree -hFugpafi --dirsfirst'

alias a='ack-grep'
alias b='byobu'
alias s='sudo'
alias se='sudoedit'
alias v='gvim'
alias m='less -S'
alias zm='zless -S'

alias rmf='rm -rf'

alias ga='git add'
alias gs='git status -sb'

alias ur='unicorn_rails --port=3000'
alias ng='nginx'
alias rr='touch tmp/restart.txt'

alias -g M='2>&1 | less -S'
alias -g C='| wc -l'
alias -g S='| sort'
alias -g US='| sort -u'

