#!/bin/zsh

. ~/.zsh/vars

alias ls='ls --color=auto -hF'
alias ll='ls --color=auto -hFl'
alias la='ls --color=auto -hFlA'

alias t='tree -hF --dirsfirst'
alias tl='tree -hFugp --dirsfirst'
alias ta='tree -hFugpa --dirsfirst'
alias tfi='tree -hFugpafi --dirsfirst'

alias m='less -S'
alias zm='zless -S'

alias v='gvim'
alias svim='sudo gvim'

alias s='screen -DR'
alias b='byobu'

alias rmf='rm -rf'

alias ga='git add'
alias gl='git log'
alias gs='git status'
alias gp='git push'
alias gpl='git pull'

alias -g M='2>&1 | less -S'
alias -g C='| wc -l'
alias -g S='| sort'
alias -g US='| sort -u'

